# Generated by Django 6.0.6 on 2026-07-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='agreement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='agreement_file',
            field=models.FileField(blank=True, null=True, upload_to='agreements/'),
        ),
        migrations.AddField(
            model_name='site',
            name='agreement_party',
            field=models.CharField(blank=True, help_text='Who is giving the contract', max_length=300),
        ),
        migrations.AddField(
            model_name='site',
            name='cubic_feet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CFt', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='running_feet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='RFt', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='square_feet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='SFt', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='location',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='site',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='sites.contractor'),
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractors', to='sites.contractor')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractors', to='sites.site')),
            ],
        ),
    ]
