# Generated by Django 6.0.6 on 2026-06-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('joining_date', models.DateField()),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
