# Generated by Django 6.0.6 on 2026-07-10 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_days', models.IntegerField(default=30)),
                ('working_days', models.IntegerField()),
                ('paid_leaves', models.IntegerField(default=0)),
                ('unpaid_leaves', models.IntegerField(default=0)),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='workers.worker')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('worker', 'month')},
            },
        ),
    ]
