# Generated by Django 6.0.6 on 2026-07-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_contractor_site_agreement_date_site_agreement_file_and_more'),
        ('workers', '0007_worklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='worker_count',
        ),
        migrations.AddField(
            model_name='attendance',
            name='extra_wage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra wage for far site', max_digits=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_far_site',
            field=models.BooleanField(default=False, help_text='Check if this is a far site'),
        ),
        migrations.AddField(
            model_name='worker',
            name='subcontractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='sites.subcontractor'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='work_logs', to='workers.worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='sites.site'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
