# Generated by Django 6.0.6 on 2026-07-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_remove_worklog_worker_count_attendance_extra_wage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_far_site',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='extra_wage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra amount for far site (e.g., 150)', max_digits=10),
        ),
    ]
