# Generated by Django 6.0.6 on 2026-09-01 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_contractor_site_agreement_date_site_agreement_file_and_more'),
        ('workers', '0009_remove_attendance_is_far_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, help_text='e.g., 1st installment, completion payment, etc.')),
                ('received_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_payments', to='sites.site')),
            ],
            options={
                'ordering': ['-received_date'],
            },
        ),
    ]
